
import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS
import './globals.css'
import { Inter } from 'next/font/google'

import Footer from '@/components/layouts/Footer'
import Header from '@/components/layouts/Header'
import LeftAside from '@/components/layouts/LeftAside'
import RightAside from '@/components/layouts/RightAside'

//Import { someNamedImport } from "SomeLibrary"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {//Function start
  
  //Function return statement
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="container p-0 a_tbdr">
        <Header />
        <main className="">
          <div className="row m-0">
            <LeftAside />
            
            {children}
            
            <RightAside />
              </div>
            </main>
            <Footer />
          </div>
      </body>
    </html>
  )

}//Function End
